<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Online School</title>
    <link rel="stylesheet" href="styles.css">
</head>

<body>
<header>
    <h1>Welcome to the Online School</h1>
</header>

<#include "menu.ftlh">

<main>
    <h2>Announcements</h2>
    <p>Welcome to the Online School! This platform allows you to manage students, courses, teachers, and grades.
        Please navigate through the links above to access the different sections.</p>
</main>

<footer>
</footer>
</body>

</html>
